name: UpdateProposedApi
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: npm run update-api
    - run: npm run compile
